/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'VisualAssessor': EventHandler<{ sessionId: string; message: string; hasImages?: boolean }, { topic: 'renovation.design'; data: { sessionId: string } }>
    'StartRenovation': ApiRouteHandler<{ message: string; budget?: number; roomType?: string; style?: string; hasImages?: boolean; imageUrls?: Array<string> }, ApiResponse<200, { sessionId: string; message: string; routedTo: string }> | ApiResponse<400, { error: string }>, { topic: 'renovation.assess'; data: { sessionId: string; message: string; hasImages?: boolean } } | { topic: 'renovation.info'; data: { sessionId: string; message: string } }>
    'ProjectCoordinator': EventHandler<{ sessionId: string }, { topic: 'renovation.render'; data: { session_id: string } }>
    'InfoHandler': EventHandler<{ sessionId: string; message: string }, never>
    'GetRenovationResult': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { sessionId: string; completed: boolean; roadmap?: unknown; assessmentSummary?: unknown; infoResponse?: string; message: string }> | ApiResponse<404, { error: string }>, never>
    'GetRendering': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { sessionId: string; renderingCompleted: boolean; rendering?: { imageBase64: string; mimeType: string; prompt: string; generatedAt: string; model: string }; renderingError?: string; message: string }> | ApiResponse<404, { error: string }>, never>
    'EditRendering': EventHandler<{ session_id: string; edit_prompt: string }, never>
    'DesignPlanner': EventHandler<{ sessionId: string }, { topic: 'renovation.coordinate'; data: { sessionId: string } }>
    'GenerateRendering': EventHandler<{ session_id: string }, never>
  }
}