/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'chatResponse': MotiaStream<{ id: string; sessionId: string; role: 'user' | 'assistant' | 'system'; content: string; status: 'processing' | 'searching' | 'analyzing' | 'complete' | 'error'; searchResults?: Array<{ title: string; link: string }>; timestamp: string }>
  }

  interface Handlers {
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'WebSearch': EventHandler<{ sessionId: string; messageId: string; originalMessage: string; searchQuery: string; conversationHistory: Array<{ role: string; content: string; timestamp: string }>; timestamp: string }, { topic: 'agent-response-ready'; data: { sessionId: string; messageId: string; response: string; searchResults?: Array<{ title: string; link: string }>; timestamp: string } }>
    'ReceiveChatMessage': ApiRouteHandler<{ sessionId: string; message: string; userId: string }, ApiResponse<200, { success: boolean; sessionId: string; messageId: string; status: string }> | ApiResponse<400, { error: string }>, { topic: 'process-ai-agent'; data: { sessionId: string; messageId: string; message: string; userId: string; conversationHistory: Array<{ role: string; content: string; timestamp: string }>; timestamp: string } }>
    'ProcessAIAgent': EventHandler<{ sessionId: string; messageId: string; message: string; userId: string; conversationHistory: Array<{ role: string; content: string; timestamp: string }>; timestamp: string }, { topic: 'web-search-required'; data: { sessionId: string; messageId: string; originalMessage: string; searchQuery: string; conversationHistory: Array<{ role: string; content: string; timestamp: string }>; timestamp: string } } | { topic: 'agent-response-ready'; data: { sessionId: string; messageId: string; response: string; searchResults?: Array<{ title: string; link: string }>; timestamp: string } }>
    'GetConversation': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { sessionId: string; messages: Array<{ role: string; content: string; timestamp: string }> }> | ApiResponse<404, { error: string }>, never>
    'FinalizeResponse': EventHandler<{ sessionId: string; messageId: string; response: string; searchResults?: Array<{ title: string; link: string }>; timestamp: string }, never>
    'ClearConversation': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; message: string }>, never>
  }
    
}