/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'reviewProgress': MotiaStream<{ id: string; reviewId: string; stage: 'submitted' | 'generating_draft' | 'draft_generated' | 'critiquing' | 'critique_completed' | 'refining' | 'review_completed' | 'posting_to_github' | 'completed' | 'failed'; message: string; timestamp: string; metadata?: { repository?: string; pullRequest?: number; branch?: string; progress?: number; currentAgent?: string; findings?: number; score?: number } }>
  }

  interface Handlers {
    'SendNotification': EventHandler<{ reviewId: string; repository: string; repositoryOwner: string; pullRequestNumber: number | unknown; commitSha: string; overallScore: number; recommendation: 'approve' | 'request_changes' | 'comment'; findingsCount: number; author?: string; deliveryFailed?: boolean }, never>
    'RefineReview': EventHandler<{ reviewId: string; repository: string; repositoryOwner: string; pullRequestNumber: number | unknown; commitSha: string; qualityScore: number }, { topic: 'review.completed'; data: { reviewId: string; repository: string; repositoryOwner: string; pullRequestNumber: number | unknown; commitSha: string; overallScore: number; recommendation: 'approve' | 'request_changes' | 'comment'; findingsCount: number } }>
    'PostGitHubFeedback': EventHandler<{ reviewId: string; repository: string; repositoryOwner: string; pullRequestNumber: number | unknown; commitSha: string; overallScore: number; recommendation: 'approve' | 'request_changes' | 'comment'; findingsCount: number }, { topic: 'review.notification'; data: { reviewId: string; repository: string; repositoryOwner: string; pullRequestNumber: number | unknown; commitSha: string; overallScore: number; recommendation: 'approve' | 'request_changes' | 'comment'; findingsCount: number; author?: string; deliveryFailed?: boolean } }>
    'GenerateDraftReview': EventHandler<{ reviewId: string; repository: string; repositoryOwner: string; pullRequestNumber: number | unknown; commitSha: string; branch: string }, { topic: 'review.draft_generated'; data: { reviewId: string; repository: string; repositoryOwner: string; pullRequestNumber: number | unknown; commitSha: string; findingsCount: number } }>
    'CritiqueDraftReview': EventHandler<{ reviewId: string; repository: string; repositoryOwner: string; pullRequestNumber: number | unknown; commitSha: string; findingsCount: number }, { topic: 'review.critique_completed'; data: { reviewId: string; repository: string; repositoryOwner: string; pullRequestNumber: number | unknown; commitSha: string; qualityScore: number } }>
    'SubmitReview': ApiRouteHandler<{ action?: string; pull_request?: { number: number; title: string; body: string | unknown; head: { ref: string; sha: string }; base: { ref: string }; user: { login: string }; diff_url: string; html_url: string }; repository: { full_name: string; name: string; owner: { login: string }; private: boolean }; sender: { login: string }; diff?: string; commit_sha?: string; branch?: string }, ApiResponse<202, { reviewId: string; status: string; message: string; streamUrl: string }> | ApiResponse<400, { error: string; code?: string }> | ApiResponse<401, { error: string; code?: string }>, { topic: 'code_review.requested'; data: { reviewId: string; repository: string; repositoryOwner: string; pullRequestNumber: number | unknown; commitSha: string; branch: string } }>
    'ListReviews': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { reviews: Array<{ reviewId: string; repository: string; pullRequestNumber: number | unknown; branch: string; author: string; status: string; finalScore?: number; recommendation?: string; requestedAt: string; completedAt?: string }>; total: number }>, never>
    'GetReview': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { reviewId: string; repository: string; pullRequestNumber: number | unknown; branch: string; author: string; status: string; finalScore?: number; recommendation?: string; requestedAt: string; completedAt?: string; stages: Record<string, { timestamp: string }>; draft?: unknown; critique?: unknown; refined?: unknown }> | ApiResponse<404, { error: string; code?: string }>, never>
  }
    
}