/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ConnectedCarWebhook': ApiRouteHandler<{ text: string; query?: string | unknown; session_id?: string | unknown }, ApiResponse<200, { message: string; session_id: string; chunks_stored: unknown }> | ApiResponse<500, { error?: string }>, { topic: 'process-alert'; data: { session_id: string; query: string; state_group: string } }>
    'LogToSheet': EventHandler<{ session_id: string; query: string; response: string; num_chunks_used: unknown }, never>
    'ProcessAlertAgent': EventHandler<{ session_id: string; query: string; state_group: string }, { topic: 'log-result'; data: { session_id: string; query: string; response: string; num_chunks_used: unknown } }>
  }
}