/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ProcessPaymentSucceeded': EventHandler<unknown, never>
    'ProcessPaymentFailed': EventHandler<unknown, never>
    'ProcessPaymentCreated': EventHandler<unknown, never>
    'ProcessCheckoutSessionCreated': EventHandler<unknown, never>
    'Success': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown>, never>
    'StripeWebhook': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<400, unknown>, { topic: 'payment-succeeded'; data: unknown } | { topic: 'payment-failed'; data: unknown }>
    'GetPaymentStatus': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<404, unknown> | ApiResponse<500, unknown>, never>
    'DemoCheckout': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown>, never>
    'CreatePayment': ApiRouteHandler<unknown, ApiResponse<201, unknown> | ApiResponse<400, unknown> | ApiResponse<500, unknown>, { topic: 'payment-created'; data: unknown }>
    'CreateCheckoutSession': ApiRouteHandler<unknown, ApiResponse<200, unknown> | ApiResponse<400, unknown> | ApiResponse<500, unknown>, { topic: 'checkout-session-created'; data: unknown }>
    'Cancel': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown>, never>
  }
}