/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ProcessOrder': EventHandler<{ orderId: string; userId: string; userEmail: string; productId: string; quantity: number; status: string; createdAt: string; userContext: { userId: string; email: string; role: string } }, never>
    'UpdateUser': ApiRouteHandler<{ name?: string; email?: string }, ApiResponse<200, { message: string; updatedBy: { userId: string; email: string; role: string } }> | ApiResponse<403, { error: string; message: string }>, never>
    'PublicContent': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { content: Array<{ id: number; title: string; text: string; premium?: boolean }>; userContext: { authenticated: boolean; userId?: string; role?: string; message: string } }>, never>
    'Profile': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { userId: string; email: string; role: string; permissions: Array<string>; message: string }>, never>
    'GenerateToken': ApiRouteHandler<{ userId?: string; email?: string; role?: 'admin' | 'user' | 'guest'; permissions?: Array<string> }, ApiResponse<200, { token: string; decoded: { userId: string; email: string; role: string; permissions: Array<string>; iat: number; exp: number }; usage: string }>, never>
    'CreateOrder': ApiRouteHandler<{ productId: string; quantity: unknown }, ApiResponse<201, { orderId: string; status: string; message: string }>, { topic: 'order.created'; data: { orderId: string; userId: string; userEmail: string; productId: string; quantity: number; status: string; createdAt: string; userContext: { userId: string; email: string; role: string } } }>
    'AdminDashboard': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; adminUser: { userId: string; email: string; role: string }; data: { totalUsers: number; activeUsers: number; recentSignups: number } }>, never>
  }
}