/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'DirectBooking': ApiRouteHandler<{ sessionId: string; friendName: string; phoneE164: string }, ApiResponse<200, { status: 'confirmed' | 'waitlisted' | 'full' | 'already_booked'; message?: string; roster: { name: string; phoneMasked: string }[]; bookingId?: string; sessionDate?: string }> | ApiResponse<400, { error: string }> | ApiResponse<409, { error: string }> | ApiResponse<500, { error: string }>, { topic: 'booking.created'; data: { bookingId: string; sessionId: string; friendId: string; friendName: string; phoneE164: string; status: 'confirmed' | 'waitlisted'; roster: { name: string; phoneMasked: string }[] } }>
    'AdminCreateSession': ApiRouteHandler<{ date: string; startTime?: string; endTime?: string; capacity?: number; location?: string; status?: 'draft' | 'published' | 'closed' }, ApiResponse<201, { session: { id: string; date: string; startTime: string; endTime: string; capacity: number; status: string; location: unknown; createdAt: string } }> | ApiResponse<400, { error: string }> | ApiResponse<401, { error: string }> | ApiResponse<409, { error: string }> | ApiResponse<500, { error: string }>, never>
    'AdminFriendsDelete': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'AdminFriendsList': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { friends: { id: string; name: string; phone: string; phoneE164: string; active: boolean; createdAt: string }[] }> | ApiResponse<500, { error: string }>, never>
    'HandleCancellation': EventHandler<{ bookingId: string; sessionId: string; friendId: string; phoneE164: string; canceledAt: string }, { topic: 'sms.send'; data: { to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string } }>
    'CalendarDownload': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { content: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'SessionInfo': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { sessions: { session: { id: string; date: string; startTime: string; endTime: string; capacity: number; status: string; location: unknown }; roster: { name: string; phoneMasked: string }[]; stats: { confirmed: number; available: number }; waitlist?: { id: string; friendName: string; phoneMasked: string; createdAt: string }[] }[] }> | ApiResponse<500, { error: string }>, never>
    'ManualInviteTrigger': EventHandler<{ sessionId: string; friendIds?: string[]; triggeredBy?: string }, { topic: 'sms.send'; data: { to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string } }>
    'AdminSendInvites': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; friendCount: number; sent: number }> | ApiResponse<400, { error: string }> | ApiResponse<401, { error: string }> | ApiResponse<500, { error: string }>, { topic: 'sms.send'; data: { to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string } }>
    'AdminSessionInfo': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { session: unknown; roster: { id: string; friendId: string; friendName: string; phoneE164: string; phoneMasked: string; status: string; bookedAt: string }[]; stats: { confirmed: number; available: number; waitlisted: number }; waitlist: { id: string; friendId: string; friendName: string; phoneMasked: string; status: string; createdAt: string }[] }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'AdminImportFriends': ApiRouteHandler<{ friends: { name: string; phone: string }[] }, ApiResponse<200, { imported: number; errors: { name: string; phone: string; error: string }[] }> | ApiResponse<401, { error: string }> | ApiResponse<500, { error: string }>, never>
    'BookingConfirmation': EventHandler<{ bookingId: string; sessionId: string; friendId: string; friendName: string; phoneE164: string; status: 'confirmed' | 'waitlisted'; roster: { name: string; phoneMasked: string }[] }, { topic: 'sms.send'; data: { to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string } } | { topic: 'calendar.generate'; data: { sessionId: string; friendId: string; friendName: string; sessionDate: string; startTime: string; endTime: string; location?: string } }>
    'SendMorningReminder': CronHandler<{ topic: 'sms.send'; data: { to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string } }>
    'SendInviteBlast': CronHandler<{ topic: 'sms.send'; data: { to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string } }>
    'CancelFromSignedLink': ApiRouteHandler<{ token: string }, ApiResponse<200, { ok: boolean }> | ApiResponse<400, { error: string }> | ApiResponse<401, { error: string }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, { topic: 'booking.canceled'; data: { bookingId: string; sessionId: string; friendId: string; phoneE164: string; canceledAt: string } }>
    'BookFromSignedLink': ApiRouteHandler<{ token: string }, ApiResponse<200, { status: 'confirmed' | 'full' | 'waitlisted'; roster: { name: string; phoneMasked: string }[] }> | ApiResponse<400, { error: string }> | ApiResponse<401, { error: string }> | ApiResponse<409, { error: string }> | ApiResponse<500, { error: string }>, { topic: 'booking.created'; data: { bookingId: string; sessionId: string; friendId: string; friendName: string; phoneE164: string; status: 'confirmed' | 'waitlisted'; roster: { name: string; phoneMasked: string }[] } }>
    'SeedNextTuesdaySession': CronHandler<never>
    'GenerateIcs': EventHandler<{ sessionId: string; friendId: string; friendName: string; sessionDate: string; startTime: string; endTime: string; location?: string }, never>
    'SendSms': EventHandler<{ to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string }, never>
  }
}