/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UploadLeadsCSV': ApiRouteHandler<{ csvContent: string; flowName?: string; autoApproveThreshold?: number }, ApiResponse<201, { flowId: string; status: string; totalLeads: number; validLeads: number; invalidLeads: number; message: string }> | ApiResponse<400, { error: string; details?: Array<string> }>, { topic: 'leads.csv.uploaded'; data: { flowId: string; leadsCount: number } }>
    'SendIndividualEmail': ApiRouteHandler<{ customSubject?: string; customHtml?: string; customText?: string }, ApiResponse<200, { success: boolean; leadId: string; email: string; resendId?: string; message: string }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, never>
    'SendEmails': ApiRouteHandler<{ leadIds?: Array<string>; sendAllApproved?: boolean; minScore?: number; tier?: 'hot' | 'warm' | 'cold'; maxRecipients: number }, ApiResponse<202, { flowId: string; emailsQueued: number; message: string }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, { topic: 'emails.send.requested'; data: { flowId: string; emailsToSend: Array<{ leadId: string; email: string; name: string; subject: string; htmlContent: string; textContent?: string }>; isRetry?: boolean } }>
    'SendBatchEmails': EventHandler<{ flowId: string; emailsToSend: Array<{ leadId: string; email: string; name: string; subject: string; htmlContent: string; textContent?: string }>; isRetry?: boolean }, { topic: 'emails.send.complete'; data: { flowId: string; totalSent: number; totalFailed: number; isRetry: boolean } }>
    'ScoreLeads': EventHandler<{ flowId: string; leadsCount: number }, { topic: 'leads.scoring.complete'; data: { flowId: string; scoredCount: number; summary: { hot: number; warm: number; cold: number } } }>
    'RetryFailedEmails': ApiRouteHandler<Record<string, unknown>, ApiResponse<202, { flowId: string; retriedCount: number; message: string }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, { topic: 'emails.send.requested'; data: { flowId: string; emailsToSend: Array<{ leadId: string; email: string; name: string; subject: string; htmlContent: string; textContent?: string }>; isRetry?: boolean } }>
    'ProcessCSV': EventHandler<{ flowId: string; leadsCount: number }, { topic: 'leads.scoring.start'; data: { flowId: string; leadsCount: number } }>
    'NotifyCompletion': EventHandler<{ flowId: string; totalSent: number; totalFailed: number; isRetry: boolean }, never>
    'GetFlowStatus': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { flowId: string; status: string; progress: { totalLeads: number; processedLeads: number; scoredLeads: number; draftedLeads: number; approvedLeads: number; sentLeads: number; failedLeads: number }; createdAt: string; updatedAt: string; error?: string }> | ApiResponse<404, { error: string }>, never>
    'GetFlowResults': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { flowId: string; status: string; leads: Array<{ id: string; name: string; company: string; email: string; role: string; industry: string; score: number; tier: string; draft?: { subject: string; approved: boolean } }>; pagination: { total: number; limit: number; offset: number } }> | ApiResponse<404, { error: string }>, never>
    'GenerateEmailDrafts': EventHandler<{ flowId: string; scoredCount: number; summary: { hot: number; warm: number; cold: number } }, { topic: 'leads.drafts.complete'; data: { flowId: string; draftedCount: number; approvedCount: number } }>
    'DraftsReady': EventHandler<{ flowId: string; draftedCount: number; approvedCount: number }, never>
    'ApproveEmails': ApiRouteHandler<{ leadIds?: Array<string>; approveAll?: boolean; minScore?: number; tier?: 'hot' | 'warm' | 'cold' }, ApiResponse<200, { flowId: string; approvedCount: number; message: string }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, never>
  }
    
}