/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'CompleteOrder': EventHandler<never, never>
    'ApprovalWebhook': ApiRouteHandler<{ approved: boolean; approvedBy: string; notes?: string }, ApiResponse<200, { success: boolean; message: string; order?: unknown }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, { topic: 'order.approved'; data: never }>
    'AnalyzeRisk': EventHandler<never, { topic: 'order.auto_approved'; data: never }>
    'SubmitOrder': ApiRouteHandler<{ items: Array<{ name: string; price: number; quantity: number }>; customerEmail: string; total: number }, ApiResponse<201, { orderId: string; status: string; message: string }>, { topic: 'order.submitted'; data: never }>
  }
    
}