/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'WebhookTrigger': ApiRouteHandler<{ commit?: { message: string; author: string; sha: string; url: string }; repository?: { name: string; url: string }; content?: string; metadata?: Record<string, unknown> }, ApiResponse<200, { status: string; message: string }> | ApiResponse<400, { error: string }>, { topic: 'process-commit'; data: { commitId: string; content: string; metadata: Record<string, unknown> } }>
    'SlackAlert': EventHandler<{ error: string; context: string; commitId?: string }, never>
    'RagAgent': EventHandler<{ commitId: string; content: string; metadata: Record<string, unknown> }, { topic: 'append-sheet'; data: { commitId: string; status: string; timestamp: string; metadata?: Record<string, unknown> } } | { topic: 'slack-error'; data: { error: string; context: string; commitId?: string } }>
    'ProcessCommit': EventHandler<{ commitId: string; content: string; metadata: Record<string, unknown> }, { topic: 'run-rag-agent'; data: { commitId: string; content: string; metadata: Record<string, unknown> } } | { topic: 'slack-error'; data: { error: string; context: string; commitId?: string } }>
    'AppendSheet': EventHandler<{ commitId: string; status: string; timestamp: string; metadata?: Record<string, unknown> }, never>
  }
}