/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SendNotification': EventHandler<never, never>
    'ProcessTask': EventHandler<never, { topic: 'task.completed'; data: never }>
    'ListTasks': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'GetTask': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'CreateTask': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'task.created'; data: never }>
  }
    
}