/**
 * Get Rendering - Retrieve generated renovation rendering
 * Returns the photorealistic image generated by Gemini 2.5 Flash
 */

import { ApiRouteConfig, Handlers } from 'motia';
import { z } from 'zod';

export const config: ApiRouteConfig = {
  type: 'api',
  name: 'GetRendering',
  description: 'Retrieves the generated renovation rendering image',
  path: '/renovation/:sessionId/rendering',
  method: 'GET',
  emits: [],
  virtualSubscribes: ['renovation.render'],
  flows: ['home-renovation'],
  responseSchema: {
    200: z.object({
      sessionId: z.string(),
      renderingCompleted: z.boolean(),
      rendering: z.object({
        imageBase64: z.string(),
        mimeType: z.string(),
        prompt: z.string(),
        generatedAt: z.string(),
        model: z.string(),
      }).optional(),
      renderingError: z.string().optional(),
      message: z.string(),
    }),
    404: z.object({ error: z.string() }),
  },
};

export const handler: Handlers['GetRendering'] = async (req, { logger, state }) => {
  const { sessionId } = req.pathParams;

  logger.info('Fetching renovation rendering', { sessionId });

  // Check if rendering is completed
  const renderingCompleted = await state.get<boolean>(sessionId, 'renderingCompleted');
  const rendering = await state.get<any>(sessionId, 'rendering');
  const renderingError = await state.get<string>(sessionId, 'renderingError');

  if (renderingError) {
    logger.error('Rendering generation failed', { sessionId, error: renderingError });
    return {
      status: 200,
      body: {
        sessionId,
        renderingCompleted: false,
        renderingError,
        message: 'Rendering generation failed',
      },
    };
  }

  if (!renderingCompleted || !rendering) {
    logger.info('Rendering not yet completed', { sessionId });
    return {
      status: 200,
      body: {
        sessionId,
        renderingCompleted: false,
        message: 'Rendering generation is still in progress. Please check back shortly.',
      },
    };
  }

  logger.info('Returning completed rendering', { 
    sessionId,
    imageSize: rendering.imageBase64?.length || 0 
  });

  return {
    status: 200,
    body: {
      sessionId,
      renderingCompleted: true,
      rendering,
      message: 'Rendering completed successfully',
    },
  };
};

