/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'MortgageRateAlertWebhook': ApiRouteHandler<{ content: string; query?: string; metadata?: Record<string, unknown> }, ApiResponse<200, { success: boolean; message: string; traceId: string }> | ApiResponse<400, { error: string }>, { topic: 'process-mortgage-data'; data: { dataId: string; content: string; query: string; hasQuery: boolean } }>
    'StoreEmbeddings': EventHandler<{ dataId: string; chunks: Array<string>; query: string }, { topic: 'query-and-analyze'; data: { dataId: string; query: string } }>
    'SendAnalysisEmail': EventHandler<{ dataId: string; query: string; analysis: string; contextCount: number; timestamp: string }, never>
    'SendMortgageAlerts': EventHandler<{ changes: Array<{ current: { lender: string; product: string; rate: number; apr: number; points: number; source: string; timestamp: string }; previous: { lender: string; product: string; rate: number; apr: number; points: number; source: string; timestamp: string }; change: number }>; timestamp: string }, never>
    'ProcessMortgageData': EventHandler<{ dataId: string; content: string; query: string; hasQuery: boolean }, { topic: 'store-embeddings'; data: { dataId: string; chunks: Array<string>; query: string } }>
    'LogResults': EventHandler<{ dataId: string; query: string; analysis: string; contextCount: number; timestamp: string }, never>
    'getRecent': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'FetchMortgageRates': CronHandler<{ topic: 'rate-changes-detected'; data: { changes: Array<{ current: { lender: string; product: string; rate: number; apr: number; points: number; source: string; timestamp: string }; previous: { lender: string; product: string; rate: number; apr: number; points: number; source: string; timestamp: string }; change: number }>; timestamp: string } }>
    'AnalyzeData': EventHandler<{ dataId: string; query: string }, { topic: 'log-results'; data: { dataId: string; query: string; analysis: string; contextCount: number; timestamp: string } } | { topic: 'send-analysis'; data: { dataId: string; query: string; analysis: string; contextCount: number; timestamp: string } }>
  }
}