/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SendSms': EventHandler<{ to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string }, never>
    'HandleCancellation': EventHandler<{ bookingId: string; sessionId: string; friendId: string; phoneE164: string; canceledAt: string }, { topic: 'sms.send'; data: { to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string } } | { topic: 'calendar.generate'; data: { sessionId: string; friendId: string; friendName: string; sessionDate: string; startTime: string; endTime: string; location?: string } }>
    'GenerateCalendar': EventHandler<{ sessionId: string; friendId: string; friendName: string; sessionDate: string; startTime: string; endTime: string; location?: string }, never>
    'ConfirmBooking': EventHandler<{ bookingId: string; sessionId: string; friendId: string; friendName: string; phoneE164: string; status: 'confirmed' | 'waitlisted'; roster: Array<{ name: string; phoneMasked: string }> }, { topic: 'sms.send'; data: { to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string } } | { topic: 'calendar.generate'; data: { sessionId: string; friendId: string; friendName: string; sessionDate: string; startTime: string; endTime: string; location?: string } }>
    'SendMorningReminder': CronHandler<{ topic: 'sms.send'; data: { to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string } }>
    'SendInviteBlast': CronHandler<{ topic: 'sms.send'; data: { to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string } }>
    'SeedNextSession': CronHandler<never>
    'ListSessions': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<500, unknown>, never>
    'GetSessions': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { sessions: Array<{ session: { id: string; date: string; startTime: string; endTime: string; capacity: number; status: 'draft' | 'published' | 'closed'; location: string | unknown; createdAt: string }; roster: Array<{ name: string; phoneMasked: string }>; stats: { confirmed: number; available: number }; waitlist?: Array<{ id: string; friendName: string; phoneMasked: string; createdAt: string }> }> }> | ApiResponse<500, unknown>, never>
    'DownloadCalendar': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { content: string }> | ApiResponse<404, unknown> | ApiResponse<500, unknown>, never>
    'CancelBooking': ApiRouteHandler<{ token: string }, ApiResponse<200, { ok: boolean }> | ApiResponse<400, unknown> | ApiResponse<401, unknown> | ApiResponse<404, unknown> | ApiResponse<500, unknown>, { topic: 'booking.canceled'; data: { bookingId: string; sessionId: string; friendId: string; phoneE164: string; canceledAt: string } }>
    'CancelBookingDirect': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<400, unknown> | ApiResponse<403, unknown> | ApiResponse<404, unknown> | ApiResponse<500, unknown>, { topic: 'booking.canceled'; data: { bookingId: string; sessionId: string; friendId: string; phoneE164: string; canceledAt: string } }>
    'BookSession': ApiRouteHandler<{ sessionId: string; friendName: string; phoneE164: string }, ApiResponse<200, { status: 'confirmed' | 'waitlisted' | 'full' | 'already_booked'; message?: string; roster: Array<{ name: string; phoneMasked: string }>; bookingId?: string; sessionDate?: string }> | ApiResponse<400, unknown> | ApiResponse<409, unknown> | ApiResponse<500, unknown>, { topic: 'booking.created'; data: { bookingId: string; sessionId: string; friendId: string; friendName: string; phoneE164: string; status: 'confirmed' | 'waitlisted'; roster: Array<{ name: string; phoneMasked: string }> } }>
    'TriggerInvites': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; friendCount: number; sent: number }> | ApiResponse<400, unknown> | ApiResponse<500, unknown>, { topic: 'sms.send'; data: { to: string; body: string; type: 'invite' | 'confirmation' | 'reminder' | 'promotion' | 'cancellation'; dedupeKey?: string } }>
    'ListFriends': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { friends: Array<{ id: string; name: string; phone: string; phoneE164: string; active: boolean; createdAt: string }> }> | ApiResponse<500, unknown>, never>
    'ImportFriends': ApiRouteHandler<{ friends: Array<{ name: string; phone: string }> }, ApiResponse<200, { imported: number; errors: Array<{ name: string; phone: string; error: string }> }> | ApiResponse<401, unknown> | ApiResponse<500, unknown>, never>
    'DeleteFriend': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string }> | ApiResponse<400, unknown> | ApiResponse<404, unknown> | ApiResponse<500, unknown>, never>
    'DeleteBooking': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, unknown> | ApiResponse<400, unknown> | ApiResponse<404, unknown> | ApiResponse<500, unknown>, never>
    'CreateSession': ApiRouteHandler<{ date: string; startTime: string; endTime: string; capacity: number; location?: string; status: 'draft' | 'published' | 'closed' }, ApiResponse<201, { session: unknown }> | ApiResponse<400, unknown> | ApiResponse<409, unknown> | ApiResponse<500, unknown>, never>
  }
    
}