/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'researchProgress': MotiaStream<{ id: string; queryId: string; status: 'pending' | 'reasoning' | 'executing_tool' | 'observation_received' | 'synthesizing' | 'completed' | 'failed'; iteration?: number; tool?: string; success?: boolean; observationPreview?: string; error?: string; timestamp: string }>
  }

  interface Handlers {
    'SynthesizeAnswer': EventHandler<{ queryId: string; forced?: boolean }, { topic: 'research.completed'; data: { queryId: string; success: boolean } } | { topic: 'research.query.failed'; data: { queryId: string; error: string } }>
    'SubmitResearchQuery': ApiRouteHandler<{ question: string; context?: { industry?: string; timeframe?: string; preferredSources?: Array<string>; maxIterations?: number; budget?: { maxTokens?: number; maxToolCalls?: number } } }, ApiResponse<202, { queryId: string; status: string; message: string; estimatedTime: string }> | ApiResponse<400, { error: string; details?: unknown }> | ApiResponse<500, { error: string; details?: unknown }>, { topic: 'research.query.requested'; data: { queryId: string; question: string; context?: { industry?: string; timeframe?: string; preferredSources?: Array<string>; maxIterations?: number; budget?: { maxTokens?: number; maxToolCalls?: number } } } }>
    'ReactLoopController': EventHandler<{ queryId: string; question: string; context?: { industry?: string; timeframe?: string; preferredSources?: Array<string>; maxIterations?: number; budget?: { maxTokens?: number; maxToolCalls?: number } } }, { topic: 'research.tool.execute'; data: { queryId: string; question: string; context?: unknown; tool: string; input: unknown; iterationNumber: number } } | { topic: 'research.synthesis.ready'; data: { queryId: string; forced?: boolean } } | { topic: 'research.query.failed'; data: { queryId: string; error: string } }>
    'HandleResearchFailure': EventHandler<{ queryId: string; error: string }, never>
    'HandleResearchCompletion': EventHandler<{ queryId: string; success: boolean }, never>
    'GetResearchQueryStatus': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { queryId: string; status: string; question: string; currentIteration?: number; iterations?: Array<unknown>; result?: unknown }> | ApiResponse<404, { error: string }> | ApiResponse<500, { error: string }>, never>
    'ExecuteTool': EventHandler<{ queryId: string; question: string; context?: unknown; tool: string; input: unknown; iterationNumber: number }, { topic: 'research.observation.ready'; data: { queryId: string; question: string; context?: { industry?: string; timeframe?: string; preferredSources?: Array<string>; maxIterations?: number; budget?: { maxTokens?: number; maxToolCalls?: number } } } } | { topic: 'research.query.failed'; data: { queryId: string; error: string } }>
  }
    
}