/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ScrapeLandingPage': EventHandler<{ jobId: string; url: string; options: { instagram?: { enabled: boolean; count: number }; tiktok?: { enabled: boolean; count: number; mode: 'text-to-video' | 'reference-images' | 'interpolation' | 'extension' } }; requestedAt: string }, never>
    'GenerateAd': ApiRouteHandler<{ url: string; options: { instagram?: { enabled: boolean; count: number }; tiktok?: { enabled: boolean; count: number; mode: 'text-to-video' | 'reference-images' | 'interpolation' | 'extension' } } }, ApiResponse<200, { jobId: string; status: string }> | ApiResponse<400, { error: string }>, { topic: 'ad.generation.started'; data: { jobId: string; url: string; options: { instagram?: { enabled: boolean; count: number }; tiktok?: { enabled: boolean; count: number; mode: string } }; requestedAt: string } }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
  }
    
}