/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ScrapeLandingPage': EventHandler<{ jobId: string; url: string; options: { instagram?: { enabled: boolean; count: number }; tiktok?: { enabled: boolean; count: number; mode: 'text-to-video' | 'reference-images' | 'interpolation' | 'extension' } }; requestedAt: string }, { topic: 'landing.page.scraped'; data: { jobId: string; url: string; markdown: string; screenshot: string; brandInfo: { title: string; description: string }; metadata: { title?: string; description?: string; keywords?: string }; options: { instagram?: { enabled: boolean; count: number }; tiktok?: { enabled: boolean; count: number; mode: 'text-to-video' | 'reference-images' | 'interpolation' | 'extension' } }; requestedAt: string; scrapedAt: string } }>
    'GenerateInstagramAds': EventHandler<{ jobId: string; url: string; brandName: string; industry: string; tone: string; targetAudience: string; primaryColors: Array<string>; aesthetic: string; valueProposition: string; adPrompt: string; options: { instagram?: { enabled: boolean; count: number }; tiktok?: { enabled: boolean; count: number; mode: 'text-to-video' | 'reference-images' | 'interpolation' | 'extension' } }; analyzedAt: string }, never>
    'AnalyzeBrand': EventHandler<{ jobId: string; url: string; markdown: string; screenshot: string; brandInfo: { title: string; description: string }; metadata: { title?: string; description?: string; keywords?: string }; options: { instagram?: { enabled: boolean; count: number }; tiktok?: { enabled: boolean; count: number; mode: 'text-to-video' | 'reference-images' | 'interpolation' | 'extension' } }; requestedAt: string; scrapedAt: string }, { topic: 'brand.analyzed'; data: { jobId: string; url: string; brandName: string; industry: string; tone: string; targetAudience: string; primaryColors: Array<string>; aesthetic: string; valueProposition: string; adPrompt: string; options: { instagram?: { enabled: boolean; count: number }; tiktok?: { enabled: boolean; count: number; mode: 'text-to-video' | 'reference-images' | 'interpolation' | 'extension' } }; analyzedAt: string } }>
    'GenerateAd': ApiRouteHandler<{ url: string; options: { instagram?: { enabled: boolean; count: number }; tiktok?: { enabled: boolean; count: number; mode: 'text-to-video' | 'reference-images' | 'interpolation' | 'extension' } } }, ApiResponse<200, { jobId: string; status: string }> | ApiResponse<400, { error: string }>, { topic: 'ad.generation.started'; data: { jobId: string; url: string; options: { instagram?: { enabled: boolean; count: number }; tiktok?: { enabled: boolean; count: number; mode: 'text-to-video' | 'reference-images' | 'interpolation' | 'extension' } }; requestedAt: string } }>
  }
    
}