/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'cursorPosition': MotiaStream<{ id: string; x: number; y: number; username: string; color: string; lastUpdated: string }>
  }

  interface Handlers {
    'UpdateCursor': ApiRouteHandler<{ roomName: string; userId: string; x: number; y: number; username: string; color?: string }, ApiResponse<200, { id: string; x: number; y: number; username: string; color: string; lastUpdated: string }> | ApiResponse<400, { error: string }>, never>
    'OnCursorLeft': EventHandler<{ roomName: string; userId: string }, never>
    'OnCursorJoined': EventHandler<{ roomName: string; userId: string; username: string; color: string }, never>
    'LeaveRoom': ApiRouteHandler<{ roomName: string; userId: string }, ApiResponse<200, { success: boolean }> | ApiResponse<400, { error: string }>, { topic: 'cursor-left'; data: { roomName: string; userId: string } }>
    'JoinRoom': ApiRouteHandler<{ roomName: string; userId: string; username: string; color?: string }, ApiResponse<200, { success: boolean; cursor: { id: string; x: number; y: number; username: string; color: string; lastUpdated: string }; existingCursors: Array<{ id: string; x: number; y: number; username: string; color: string; lastUpdated: string }> }> | ApiResponse<400, { error: string }>, { topic: 'cursor-joined'; data: { roomName: string; userId: string; username: string; color: string } }>
    'ClearRoom': ApiRouteHandler<{ roomName: string }, ApiResponse<200, { success: boolean; cleared: number }> | ApiResponse<400, { error: string }>, never>
  }
    
}