/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'Card Requirements Validator': EventHandler<{ id: string; name: string; desc: string; members: Array<{}> }, never>
    'Trello Webhook Handler': ApiRouteHandler<{ action: { type: 'createCard' | 'updateCard' | 'commentCard' | 'addMemberToCard' | 'updateCustomFieldItem'; data: { card: { id: string }; text?: string; list?: { id: string } }; display?: { entities?: { memberCreator: { username: string } } } } }, unknown, { topic: 'card.created'; data: { id: string; name: string; desc: string; members: Array<{}> } } | { topic: 'card.updateCustomFieldItem'; data: { id: string; customFieldItem?: { idCustomField: string; idValue: unknown } } } | { topic: 'card.commented'; data: { card: { id: string; list: { id: string } }; comment: { text: string; idMember: string } } } | { topic: 'member.assigned'; data: { id: string } }>
    'Trello Webhook Validation': ApiRouteHandler<{}, unknown, never>
    'Start Assigned Card': EventHandler<{ id: string }, never>
    'Slack Notifier': EventHandler<{ channel: string; message: string }, never>
    'Mark Card For Review': EventHandler<{ id: string; customFieldItem?: { idCustomField: string; idValue: unknown } }, { topic: 'notify.slack'; data: { channel: string; message: string } }>
    'Complete Approved Card': EventHandler<{ card: { id: string; list: { id: string } }; comment: { text: string; idMember: string } }, never>
    'Check Overdue Cards': CronHandler<never>
  }
}