/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SendTelegramNotification': EventHandler<{ messageId: string; from: string; subject: string; snippet: string; timestamp: string; analysis: { urgencyLevel: 'critical' | 'high' | 'medium' | 'low'; category: string; summary: string; reason: string } }, never>
    'PollGmail': CronHandler<{ topic: 'analyze-email'; data: { messageId: string; from: string; subject: string; snippet: string; timestamp: string; labels: Array<string> } }>
    'AnalyzeEmail': EventHandler<{ messageId: string; from: string; subject: string; snippet: string; timestamp: string; labels: Array<string> }, { topic: 'send-telegram-notification'; data: { messageId: string; from: string; subject: string; snippet: string; timestamp: string; analysis: { urgencyLevel: 'critical' | 'high' | 'medium' | 'low'; category: string; summary: string; reason: string } } }>
  }
    
}