/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'todo': MotiaStream<{ id: string; title: string; description?: string; status: 'pending' | 'in_progress' | 'completed' | 'archived'; priority: 'low' | 'medium' | 'high'; dueDate?: string; createdAt: string; updatedAt: string; completedAt?: string }>
  }

  interface Handlers {
    'UpdateTodo': ApiRouteHandler<{ title?: string; description?: string; status?: 'pending' | 'in_progress' | 'completed' | 'archived'; priority?: 'low' | 'medium' | 'high'; dueDate?: string }, ApiResponse<200, { id: string; title: string; description?: string; status: 'pending' | 'in_progress' | 'completed' | 'archived'; priority: 'low' | 'medium' | 'high'; dueDate?: string; createdAt: string; updatedAt: string; completedAt?: string }> | ApiResponse<400, { error: string }> | ApiResponse<404, { error: string }>, { topic: 'todo-updated'; data: { todoId: string; updates: { title?: string; description?: string; status?: string; priority?: string; dueDate?: string }; timestamp: string } } | { topic: 'todo-completed'; data: { todoId: string; title: string; completedAt: string } } | { topic: 'track-analytics'; data: { event: string; todoId: string; timestamp: string; priority?: string; previousStatus?: string; newStatus?: string; status?: string } }>
    'TodoUpdatedHandler': EventHandler<{ todoId: string; updates: { title?: string; description?: string; status?: string; priority?: string; dueDate?: string }; timestamp: string }, never>
    'TodoDeletedHandler': EventHandler<{ todoId: string; title: string; timestamp: string }, never>
    'TodoCreatedNotification': EventHandler<{ todoId: string; title: string; priority: 'low' | 'medium' | 'high' }, { topic: 'notification-sent'; data: { todoId: string; channels: Array<string>; sentAt: string; message?: string } }>
    'TodoCompletedWorkflow': EventHandler<{ todoId: string; title: string; completedAt: string }, { topic: 'achievement-unlocked'; data: { userId: string; achievement: string; todoId: string; unlockedAt: string } } | { topic: 'notification-sent'; data: { todoId: string; channels: Array<string>; sentAt: string; message?: string } }>
    'NotificationSentLogger': EventHandler<{ todoId: string; channels: Array<string>; sentAt: string; message?: string }, never>
    'ListTodos': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { todos: Array<{ id: string; title: string; description?: string; status: 'pending' | 'in_progress' | 'completed' | 'archived'; priority: 'low' | 'medium' | 'high'; dueDate?: string; createdAt: string; updatedAt: string; completedAt?: string }>; count: number }>, never>
    'GetTodo': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { id: string; title: string; description?: string; status: 'pending' | 'in_progress' | 'completed' | 'archived'; priority: 'low' | 'medium' | 'high'; dueDate?: string; createdAt: string; updatedAt: string; completedAt?: string }> | ApiResponse<404, { error: string }>, never>
    'GetTodoStats': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { total: number; pending: number; inProgress: number; completed: number; archived: number }>, never>
    'DeleteTodo': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; message: string }> | ApiResponse<404, { error: string }>, { topic: 'todo-deleted'; data: { todoId: string; title: string; timestamp: string } } | { topic: 'track-analytics'; data: { event: string; todoId: string; timestamp: string; priority?: string; previousStatus?: string; newStatus?: string; status?: string } }>
    'DailyStatsCron': CronHandler<never>
    'CreateTodo': ApiRouteHandler<{ title: string; description?: string; priority: 'low' | 'medium' | 'high'; dueDate?: string }, ApiResponse<201, { id: string; title: string; description?: string; status: 'pending' | 'in_progress' | 'completed' | 'archived'; priority: 'low' | 'medium' | 'high'; dueDate?: string; createdAt: string; updatedAt: string; completedAt?: string }> | ApiResponse<400, { error: string }>, { topic: 'todo-created'; data: { todoId: string; title: string; priority: 'low' | 'medium' | 'high' } } | { topic: 'track-analytics'; data: { event: string; todoId: string; timestamp: string; priority?: string; previousStatus?: string; newStatus?: string; status?: string } }>
    'TodoCleanupCron': CronHandler<{ topic: 'cleanup-completed'; data: { archivedCount: number; durationMs: number; runAt: string } }>
    'CleanupCompletedHandler': EventHandler<{ archivedCount: number; durationMs: number; runAt: string }, never>
    'AnalyticsTracker': EventHandler<{ event: string; todoId: string; timestamp: string; priority?: string; previousStatus?: string; newStatus?: string; status?: string }, never>
    'AchievementHandler': EventHandler<{ userId: string; achievement: string; todoId: string; unlockedAt: string }, never>
  }
    
}